-- Generated by Neovim Theme Generator

vim.cmd('hi clear')
vim.g.colors_name = 'forrest-devin'

-- Color palette
local c = {
  fg = '#cfcfcf',
  bg = 'NONE',
  comment = '#787878',
  green = '#437a38',
  green_light = '#a5c19f',
  green_dark = '#0d2610',
  green_darker = '#051b04',
  orange = '#f2bd4a',
  orange_dark = '#d78233',
  orange_muted = '#d19a66',
  yellow = '#e5c07b',
  red = '#e06c75',
  gray = '#555555',
  operator = '#c0c0c0',
}

local function hl(name, opts)
  vim.api.nvim_set_hl(0, name, opts)
end

-- UI Elements
hl('Normal', { fg = c.fg, bg = c.bg })
hl('CursorLine', { bg = c.bg })
hl('CursorLineNr', { fg = c.orange, bold = true })
hl('LineNr', { fg = c.gray })
hl('Visual', { bg = c.green_dark })
hl('Search', { fg = '#000000', bg = c.yellow })
hl('IncSearch', { fg = '#000000', bg = c.yellow })
hl('SignColumn', { bg = '#000000' })
hl('Pmenu', { fg = c.fg, bg = c.green_darker })
hl('PmenuSel', { fg = c.fg, bg = c.green_dark })
hl('StatusLine', { fg = c.fg, bg = c.bg })
hl('StatusLineNC', { fg = c.gray, bg = c.bg })
hl('WinSeparator', { fg = c.orange })
hl('Cursor', { fg = '#000000', bg = c.orange })

-- Syntax
hl('Comment', { fg = c.comment, italic = true })
hl('String', { fg = c.orange_dark })
hl('Number', { fg = c.orange_muted })
hl('Boolean', { fg = c.orange_muted })
hl('Identifier', { fg = c.fg })
hl('Function', { fg = c.green_light })
hl('Keyword', { fg = c.green })
hl('Operator', { fg = c.operator })
hl('Type', { fg = c.orange })
hl('Constant', { fg = c.green_light })
hl('Statement', { fg = c.green })
hl('PreProc', { fg = c.green })
hl('Special', { fg = c.green_light })

-- Treesitter
hl('@comment', { link = 'Comment' })
hl('@string', { link = 'String' })
hl('@number', { link = 'Number' })
hl('@boolean', { link = 'Boolean' })
hl('@function', { link = 'Function' })
hl('@function.call', { fg = c.green_light })
hl('@method', { link = 'Function' })
hl('@keyword', { link = 'Keyword' })
hl('@variable', { fg = c.fg })
hl('@parameter', { fg = c.fg })
hl('@type', { link = 'Type' })
hl('@type.builtin', { fg = c.orange })
hl('@property', { fg = c.fg })
hl('@field', { fg = c.fg })
hl('@operator', { link = 'Operator' })
hl('@punctuation', { fg = c.fg })
hl('@constant', { link = 'Constant' })
hl('@constant.builtin', { fg = c.green_light })

-- Markdown
hl('@markup.heading', { fg = c.orange, bold = true })
hl('@markup.heading.1', { fg = c.orange, bold = true })
hl('@markup.heading.2', { fg = c.orange, bold = true })
hl('@markup.heading.3', { fg = c.orange, bold = true })
hl('@text.title', { fg = c.orange, bold = true })

-- Diagnostics
hl('DiagnosticError', { fg = c.red })
hl('DiagnosticWarn', { fg = c.yellow })
hl('DiagnosticInfo', { fg = c.orange })
hl('DiagnosticHint', { fg = c.orange })
hl('DiagnosticUnderlineError', { undercurl = true, sp = c.red })
hl('DiagnosticUnderlineWarn', { undercurl = true, sp = c.yellow })

-- Telescope
hl('TelescopeBorder', { fg = c.green })
